//Authorizing User
export const AUTH_SIGNUP_START = "AUTH_SIGNUP_START";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_FAIL = "AUTH_SIGNUP_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH = "AUTH";

//User
export const GET_USER_DATA = "GET_USER_DATA";

//Community Chat
export const ADD_TO_COMMUNITY_CHAT = "ADD_TO_COMMUNITY_CHAT";
export const DELETE_FROM_COMMUNITY_CHAT = 'DELETE_FROM_COMMUNITY_CHAT';
export const GET_COMMUNITY_CHAT = 'GET_COMMUNITY_CHAT';
export const ADD_COMMUNITY_VOTE = 'ADD_COMMUNITY_VOTE';

// USER CHAT
export const ADD_TO_USER_CHAT = 'ADD_TO_USER_CHAT';
export const DELETE_FROM_USER_CHAT = 'DELETE_FROM_USER_CHAT';
export const GET_USER_CHAT = 'GET_USER_CHAT';

//cards
export const ADD_CARD_TO_CURRENTS = 'ADD_CARD_TO_CURRENTS';
export const ADD_CURRENT = 'ADD_CURRENT';
export const REMOVE_CURRENT = 'REMOVE_CURRENT';
export const CLEAR_CURRENTS = 'CLEAR_CURRENTS';
export const PICK_NEW_RANDOM = 'PICK_NEW_RANDOM';
export const CHOOSE_CARD = 'CHOOSE_CARD';
export const UPDATE_CURRENT_CARDS = 'UPDATE_CURRENT_CARDS';
export const UPDATE_CARD = "UPDATE_CARD";

export const GET_USER_CARDS = "GET_USER_CARDS";
export const GET_CURRENT_CARDS = 'GET_CURRENT_CARDS';

//other
export const RESET_ALL = "RESET_ALL";

//test
export const TEST = "TEST";

export const SEARCH= "SEARCH";